### ISSUE TITLE
Please upgrade json_serializable and json_annotation

### ISSUE THREAD

**Issue by LeGoffMael** [stipop-development/stipop-flutter-sdk#8]
**Describe the bug**
You are using a passed versions of `json_serializable` and `json_annotation` dependencies.
Because of this we are facing version conflict with other plugins and cannot use `stipop-sdk`.

**Expected behavior**
Please consider using json_serializable 6.x.x

**Comment by hojunjeong90** [comment]
I will proceed the update from 0.2.1 or 0.3.0. The update will be done within the next week. Thank you!
